app:
  kafka:
    consumer:
      topic: DigitalProduct.eventstreaming-test.test-topic
spring:
  kafka:
    consumer:
      group-id: eventstreaming-test-1
    properties:
      ssl:
        endpoint:
          identification:
            algorithm:

